/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package air.canada;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.*;
import java.awt.Color;
import java.io.IOException;


/**
 * @author sprince
 */
public class Plan extends javax.swing.JFrame {
    File nameSave = new File("nameList.txt");

    /**
     * Creates new form Chart
     */
    public Plan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    void aToHButtonsAction(ActionEvent event) {
        // get the reference of the button which invoked this method call.
        JButton button = (JButton) event.getSource();

        if(button.getText().equals("X")){
            // Seat is already taken
            int result = JOptionPane.showConfirmDialog(this,"Do you want to remove the Passenger?", "Air Canada",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                String seatName = button.getName();
                button.setText(seatName);
                button.setName(seatName); // Name of the button is a different parameter than the Text (which appears on the button)
                button.addActionListener(this::aToHButtonsAction);

                JButton tempButton = new JButton(); //to get the default background color of a JButton.

                button.setBackground(tempButton.getBackground()); // assign the default background co
            }


        }else{
            // Seat is vacant

        //Brings up message
        String firstName = JOptionPane.showInputDialog(null, "Please enter your first name.");
        //input
        System.out.println(firstName);
        //Brings up message
        String lastName = JOptionPane.showInputDialog(null, "Please enter your last name.");
        //input
        System.out.println(lastName);
        //output ___ has been assigned
        JOptionPane.showMessageDialog(rootPane, firstName + " " + lastName + " has been assigned to seat " + button.getText() + "!");

        //change colour of button
        button.setBackground(Color.red);
        //keep text black
        button.setForeground(Color.black);
        //change text to X
        button.setText("X");
        }
    }



    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        seat = new JButton[8][10];
        String[] seatLabels = {"A", "B", "C", "D", "E", "F", "G", "H"};
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 10; j++) {
                String seatName = seatLabels[i] + (j + 1);

                JButton button =  new JButton();
                button.setText(seatName);
                button.setName(seatName);
                button.setFont(new java.awt.Font("Arial", 0, 18));
                button.addActionListener(this::aToHButtonsAction);

                seat[i][j] = button;
            }
        }

        aisles = new JLabel[12];
        for (int i = 0; i < aisles.length; i++) {
            JLabel aisle = new JLabel("" + (i + 1));
            aisle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            aisle.setForeground(new java.awt.Color(255, 0, 0));
            aisles[i] = aisle;

        }

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        chartLbl = new javax.swing.JLabel();


        manifest = new javax.swing.JButton();
        waitlist = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("jMenu6");

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar6.add(jMenu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chartLbl.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        chartLbl.setForeground(new java.awt.Color(255, 51, 51));
        chartLbl.setText("Air Canada");


        manifest.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        manifest.setForeground(new java.awt.Color(255, 51, 51));
        manifest.setText("VIEW MANIFEST");
        manifest.setBorderPainted(false);
        manifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manifestActionPerformed(evt);
            }
        });

        waitlist.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        waitlist.setForeground(new java.awt.Color(255, 51, 51));
        waitlist.setText("VIEW WAITLIST");
        waitlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 51, 51));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(aisles[0], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(aisles[1], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(aisles[2], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(aisles[3], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(aisles[4], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(aisles[5], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(aisles[6], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(aisles[7], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(aisles[8], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(aisles[9], javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][0])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][0]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][1])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][1]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][2])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][2]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][3])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][3]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][4])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][4]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][5])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][5]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][6])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][6]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][7])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][7]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][8])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][8]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[0][9])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(seat[1][9])))
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][7])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][7])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][7]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][6])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][6])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][6]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][5])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][5])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][5]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][4])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][4])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][4]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][3])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][3])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][3]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][2])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][2])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][2]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][1])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][1])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][1], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][0])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][0])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][0]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][8])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][8])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][8]))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seat[2][9])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[3][9])
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seat[4][9])))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(seat[5][0])
                                                        .addComponent(seat[5][1])
                                                        .addComponent(seat[5][2])
                                                        .addComponent(seat[5][3])
                                                        .addComponent(seat[5][4])
                                                        .addComponent(seat[5][5])
                                                        .addComponent(seat[5][6])
                                                        .addComponent(seat[5][7])
                                                        .addComponent(seat[5][8])
                                                        .addComponent(seat[5][9])))
                                        .addComponent(manifest)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(128, 128, 128)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(waitlist)
                                                        .addComponent(chartLbl))))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][9])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][9]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][8])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][8]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][7])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][7]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][6])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][6]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][5])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][5]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][4])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][4]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][3])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][3]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][2])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][2]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][0])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][0]))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(seat[6][1])
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seat[7][1])))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(chartLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(seat[0][0])
                                                        .addComponent(aisles[0])
                                                        .addComponent(seat[1][0])
                                                        .addComponent(seat[2][0])
                                                        .addComponent(seat[3][0])
                                                        .addComponent(seat[4][0])
                                                        .addComponent(seat[5][0])
                                                        .addComponent(seat[6][0])
                                                        .addComponent(seat[7][0]))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(seat[0][1])
                                                        .addComponent(aisles[1])
                                                        .addComponent(seat[1][1])
                                                        .addComponent(seat[2][1])
                                                        .addComponent(seat[3][1])
                                                        .addComponent(seat[4][1])
                                                        .addComponent(seat[5][1])
                                                        .addComponent(seat[6][1])
                                                        .addComponent(seat[7][1]))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(seat[0][2])
                                                        .addComponent(aisles[2])
                                                        .addComponent(seat[1][2])
                                                        .addComponent(seat[2][2])
                                                        .addComponent(seat[3][2])
                                                        .addComponent(seat[4][2])
                                                        .addComponent(seat[5][2])
                                                        .addComponent(seat[6][2])
                                                        .addComponent(seat[7][2]))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(seat[0][3])
                                                        .addComponent(aisles[3])
                                                        .addComponent(seat[1][3])
                                                        .addComponent(seat[2][3])
                                                        .addComponent(seat[3][3])
                                                        .addComponent(seat[4][3])
                                                        .addComponent(seat[5][3])
                                                        .addComponent(seat[6][3])
                                                        .addComponent(seat[7][3]))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(seat[0][4])
                                                        .addComponent(seat[1][4])
                                                        .addComponent(seat[2][4])
                                                        .addComponent(seat[3][4])
                                                        .addComponent(seat[4][4])
                                                        .addComponent(seat[5][4])
                                                        .addComponent(seat[6][4])
                                                        .addComponent(seat[7][4])))
                                        .addComponent(aisles[4]))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(seat[0][5])
                                        .addComponent(aisles[5])
                                        .addComponent(seat[1][5])
                                        .addComponent(seat[2][5])
                                        .addComponent(seat[3][5])
                                        .addComponent(seat[4][5])
                                        .addComponent(seat[5][5])
                                        .addComponent(seat[6][5])
                                        .addComponent(seat[7][5]))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(seat[0][6])
                                        .addComponent(aisles[6])
                                        .addComponent(seat[1][6])
                                        .addComponent(seat[2][6])
                                        .addComponent(seat[3][6])
                                        .addComponent(seat[4][6])
                                        .addComponent(seat[5][6])
                                        .addComponent(seat[6][6])
                                        .addComponent(seat[7][6]))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(seat[0][7])
                                        .addComponent(aisles[7])
                                        .addComponent(seat[1][7])
                                        .addComponent(seat[2][7])
                                        .addComponent(seat[3][7])
                                        .addComponent(seat[4][7])
                                        .addComponent(seat[5][7])
                                        .addComponent(seat[6][7])
                                        .addComponent(seat[7][7]))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(seat[0][8])
                                        .addComponent(aisles[8])
                                        .addComponent(seat[1][8])
                                        .addComponent(seat[2][8])
                                        .addComponent(seat[3][8])
                                        .addComponent(seat[4][8])
                                        .addComponent(seat[5][8])
                                        .addComponent(seat[6][8])
                                        .addComponent(seat[7][8]))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(seat[0][9])
                                        .addComponent(aisles[9])
                                        .addComponent(seat[1][9])
                                        .addComponent(seat[2][9])
                                        .addComponent(seat[3][9])
                                        .addComponent(seat[4][9])
                                        .addComponent(seat[5][9])
                                        .addComponent(seat[6][9])
                                        .addComponent(seat[7][9]))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(manifest)
                                        .addComponent(waitlist)
                                        .addComponent(exitBtn))
                                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>


    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {

        //exit program
        int result = JOptionPane.showConfirmDialog(null, "Would you like to exit?", "Exit?", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }

    private void manifestActionPerformed(java.awt.event.ActionEvent evt) {

        //output
        JOptionPane.showMessageDialog(rootPane, "Added to Manifest!");

    }

    private void waitlistActionPerformed(java.awt.event.ActionEvent evt) {

        JOptionPane.showMessageDialog(rootPane, " has been added to waitlist!");


    }

    public void checkFile() {
        try {
            if (nameSave.exists() == false) {
                nameSave.createNewFile();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "File not found");
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton[][] seat;
    private javax.swing.JLabel aisles[];

    private javax.swing.JLabel chartLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JButton manifest;
    private javax.swing.JButton waitlist;
    // End of variables declaration
}
